name: stock_sayar
description: A stock counting application

publish_to: 'none'

version: 1.21.02+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.2.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  battery_plus: ^7.0.0
  http: ^1.1.0
  intl: ^0.18.1
  csv: ^5.0.3
  collection: ^1.18.0
  sqflite: ^2.3.0
  path: ^1.8.3    
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/alphega_logo120.png
    - assets/images/crossist_stok_sayim120.png
    - assets/icon/icon.png
  
